### ISSUE TITLE
AA.csv file from Fasi

### ISSUE THREAD

**Issue by fasiRahim** [AtulMalakar/Feed-Template-For-BO#1]
[AA.csv](https://github.com/AtulMalakar/Feed-Template-For-BO/files/12524331/AA.csv)

**Comment by fasiRahim** [comment]
code : dataFrame = pd.read_csv('./AA.csv', encoding='utf-8')  not work with the AA.csv file,
but it works with on_bad_lines='skip'

**Comment by AtulMalakar** [comment]
The CSV looks distorted. Few fields have jumbled here and there. Try re-organizing the CSV manually, and remove all the rows that have blank data or securities that are delisted.

I've done that for you. Check attached CSV and try to run the code on this.


[AA-Organized.csv](https://github.com/AtulMalakar/Feed-Template-For-BO/files/12532801/AA-Organized.csv)

**Comment by fasiRahim** [comment]
Thanks for your Support, The Issue is resolved
